---
server:
  host: 127.0.0.1
  port: 8080

log:
  level: info
  format: console

tvheadend:
  scheme: http
  host: <tvheadend_host>
  port: 9981
  username: <tvheadend_username>
  password: <tvheadend_password>

database:
  path: ./tvhgo.db

auth:
  session:
    cookie_name: tvhgo_session
    cookie_secure: false
    maximum_inactive_lifetime: 168h
    maximum_lifetime: 720h
    token_rotation_interval: 30m
    cleanup_interval: 12h

  totp:
    issuer: tvhgo

  reverse_proxy:
    enabled: false
    user_header: Remote-User
    email_header: Remote-Email
    name_header: Remote-Name
    allowed_proxies: ["127.0.0.0/24", "127.0.0.1"]
    allow_registration: false

metrics:
  enabled: true
  path: /metrics
  port: 8081
  host: 127.0.0.1
  token: <metrics_token>
