export enum TestIds {
  PAGINATION_FIRST_PAGE = 'pagination-first-page-btn',
  PAGINATION_PREVIOUS_PAGE = 'pagination-previous-page-btn',
  PAGINATION_NEXT_PAGE = 'pagination-next-page-btn',
  PAGINATION_LAST_PAGE = 'pagination-last-page-btn',
  REVOKE_SESSION_BUTTON = 'revoke-session-btn',
  REVOKE_TOKEN_BUTTON = 'revoke-token-btn',
  THEME_DROPDOWN = 'theme-dropdown',
  LANGUAGE_DROPDOWN = 'language-dropdown',
  TIME_FORMAT_DROPDOWN = 'time-format-dropdown',
  LOGOUT_BUTTON = 'logout-button',
  SAVE_USER_BUTTON = 'save-user-btn',
  TWOFA_DISABLE_BUTTON = 'twofa-disable-button',
  TWOFA_ENABLE_BUTTON = 'twofa-enable-button',
  SELECT_ALL_RECORDINGS_CHECKBOX = 'select-all-recordings-checkbox',
  SELECT_RECORDING_CHECKBOX = 'select-recording-checkbox',
  DELETE_CANCEL_RECORDINGS_BUTTON = 'delete-cancel-recordings-btn',
  CONFIRM_DELETE_BUTTON = 'confirm-delete-btn',
  RECORDINGS_STATUS_DROPDOWN = 'recordings-status-dropdown',
}
