{
 "title": "tvhgo",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(tvhgo_tvheadend_total_connections,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tvhgo_tvheadend_total_connections{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tvhgo_tvheadend_total_subscriptions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total inputs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tvhgo_tvheadend_total_inputs{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Errors per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_subscription_errors{job=\"$job\", hostname!=\"\"}) by (hostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwith (bit/s) per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_subscription_in{job=\"$job\", hostname!=\"\"}) by (hostname)",
     "legendFormat": "IN: {{hostname}}"
    },
    {
     "expr": "-sum(tvhgo_tvheadend_subscription_out{job=\"$job\", hostname!=\"\"}) by (hostname)",
     "legendFormat": "OUT: {{hostname}}"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_input_subscriptions{job=\"$job\"}) by (input)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bit Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_input_ber{job=\"$job\"}) by (input)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwith (bit/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_input_bps{job=\"$job\"}) by (input)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal-to-noise ratio (SNR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_input_snr{job=\"$job\"}) by (input) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_input_signal{job=\"$job\"}) by (input) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tvhgo_tvheadend_input_cc{job=\"$job\"}) by (input)",
     "legendFormat": "{{input}} - Continuity Errors"
    },
    {
     "expr": "sum(tvhgo_tvheadend_input_te{job=\"$job\"}) by (input)",
     "legendFormat": "{{input}} - Transport Errors"
    },
    {
     "expr": "sum(tvhgo_tvheadend_input_unc{job=\"$job\"}) by (input)",
     "legendFormat": "{{input}} - Uncorrected Blocks "
    }
   ]
  }
 ]
}