name: Build

on:
  push:
    branches: ["main"]

env:
  NODE_VERSION: 18.12.1
  PLATFORMS: linux/amd64,linux/arm64
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prepare
        id: prep
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build ui
        env:
          VERSION: beta
          GIT_COMMIT: ${{ steps.prep.outputs.sha_short }}
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: tvhgo-ui-${{ github.sha }}
          path: ./ui/dist


  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-ui
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ui build artifact
        uses: actions/download-artifact@v2
        with:
          name: tvhgo-ui-${{ github.sha }}
          path: ./ui/dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}, ${{ env.IMAGE_NAME }}:latest"
