name: Verify pull request

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build-ui:
    uses: ./.github/workflows/build-ui.yml
    with:
      upload_artifact: false
